# Generated by Django 6.0.4 on 2026-04-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(blank=True, help_text='Icon name for the frontend', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Floor number (for example, 4)')),
                ('name', models.CharField(blank=True, help_text="Floor name (for example, '4-th floor')", max_length=100)),
                ('map_image', models.FileField(blank=True, help_text='Файл мапи поверху (ідеально - SVG, або PNG/JPG)', null=True, upload_to='floor_maps/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='spaces.location')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="For example, 'Desk #45' or 'CARPATI'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Короткий опис простору')),
                ('space_type', models.CharField(choices=[('desk', 'Desk'), ('meeting_room', 'Meeting Room'), ('private_office', 'Private Office')], max_length=50)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Number of seats')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('svg_element_id', models.CharField(blank=True, help_text='Element ID in the SVG map', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='spaces', to='spaces.amenity')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='spaces.floor')),
            ],
        ),
    ]
